---
title: "index"
output: html_document
---

```{r,read_data,include=TRUE}
library(kableExtra)
library(dplyr)
library(formattable)
library(DT)

source("stock_overview.R")
```

```{r,output_data,echo=FALSE}
Sys.Date()

df_stocklist1 <- df_stocklist %>%
  filter(`Daily` >= 0) %>% 
  mutate(`Daily` = color_tile("transparent","green")(`Daily`))

df_stocklist2 <- df_stocklist %>%
  filter(`Daily` < 0) %>% 
  mutate(`Daily` = color_tile("red","transparent")(`Daily`))

df_stocklist <- rbind(df_stocklist1, df_stocklist2)
df_stocklist <- df_stocklist[order(df_stocklist$Name),]

df_stocklist1 <- df_stocklist %>%
  filter(`Weekly` >= 0) %>% 
  mutate(`Weekly` = color_tile("transparent","green")(`Weekly`))

df_stocklist2 <- df_stocklist %>%
  filter(`Weekly` < 0) %>% 
  mutate(`Weekly` = color_tile("red","transparent")(`Weekly`))

df_stocklist <- rbind(df_stocklist1, df_stocklist2)
df_stocklist <- df_stocklist[order(df_stocklist$Name),]

df_stocklist1 <- df_stocklist %>%
  filter(`MaxCur2020` >= 0) %>% 
  mutate(`MaxCur2020` = color_tile("transparent","green")(`MaxCur2020`))

df_stocklist2 <- df_stocklist %>%
  filter(`MaxCur2020` < 0) %>% 
  mutate(`MaxCur2020` = color_tile("red","transparent")(`MaxCur2020`))

df_stocklist <- rbind(df_stocklist1, df_stocklist2)
df_stocklist <- df_stocklist[order(df_stocklist$Name),]

df_stocklist1 <- df_stocklist %>%
  filter(MaxMin2020 >= 0) %>%
  mutate(`MaxMin2020` = color_tile("transparent","green")(`MaxMin2020`))

df_stocklist2 <- df_stocklist %>%
  filter(`MaxMin2020` < 0) %>% 
  mutate(`MaxMin2020` = color_tile("red","transparent")(`MaxMin2020`))

df_stocklist <- rbind(df_stocklist1, df_stocklist2)
df_stocklist <- df_stocklist[order(df_stocklist$Name),]

as.datatable(formattable(df_stocklist),
             class = 'cell-border stripe',
             rownames = FALSE) %>% 
  formatCurrency(c('Current','Maxtotal','Min2008','Max2020','Min2020'), currency = "€") %>%
  formatStyle('Current',  backgroundColor = 'lightgrey', fontWeight = 'bold')
```